name: Keep Render App Awake

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:       # Allows manual triggering from GitHub UI

jobs:
  ping-render:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: curl -sSf https://newsletter-1dx3.onrender.com/ || echo "Ping failed"
